"""Loss functions migrated from historical HyperTagging repositories."""

from hypertagging.losses.embedding_losses import (
    CompositeLoss,
    build_angle_matrix,
    build_distance_matrix,
    colab_intra_loss,
    colab_radius_loss,
    connection_loss_from_embeddings,
    connection_loss_from_predictions,
    grafei_inter_loss,
    grafei_intra_loss,
    grafei_radius_loss,
    toy_mc_inter_loss,
    toy_mc_radius_loss,
    vicreg_loss,
)
from hypertagging.losses.gpt_losses import distance as gpt_distance
from hypertagging.losses.gpt_losses import radius_loss as gpt_radius_loss
from hypertagging.losses.hyperbolic_pretraining import (
    HYPERBOLIC_SCALE_CONTRACT_VERSION,
    LEVEL_HEIGHT_DISTANCE_ABLATION_VERSION,
    TREE_DISTANCE_CONTRACT_VERSION,
    build_tree_relation_targets,
    covariance_regularization,
    dimension_aware_tangent_variance_target,
    hyperbolic_pretraining_loss,
    level_height_tree_distance_targets_v1,
    parent_child_margin_loss,
    parent_negative_coverage_statistics,
    topology_safe_parent_negative_mask,
    radius_depth_loss,
    radius_targets,
    variance_regularization,
)
from hypertagging.losses.level_reconstruction import level_reconstruction_loss
from hypertagging.losses.link_losses import link_cross_entropy, link_metrics, transfer_link_metrics
from hypertagging.losses.physics import invariant_mass, p4_sum_consistency_loss, soft_daughter_sum_p4
from hypertagging.losses.reconstruction_losses import (
    embedding_cosine_distance,
    embedding_mse_distance,
    get_class_weight,
    momentum_metrics,
    pdg_metrics,
    plain_momentum_metrics,
    recover_pdg,
)
from hypertagging.losses.set_matching import hungarian_or_greedy, matching_cost

__all__ = [
    "CompositeLoss",
    "build_angle_matrix",
    "build_distance_matrix",
    "colab_intra_loss",
    "colab_radius_loss",
    "connection_loss_from_embeddings",
    "connection_loss_from_predictions",
    "embedding_cosine_distance",
    "embedding_mse_distance",
    "get_class_weight",
    "gpt_distance",
    "gpt_radius_loss",
    "hungarian_or_greedy",
    "hyperbolic_pretraining_loss",
    "HYPERBOLIC_SCALE_CONTRACT_VERSION",
    "LEVEL_HEIGHT_DISTANCE_ABLATION_VERSION",
    "TREE_DISTANCE_CONTRACT_VERSION",
    "build_tree_relation_targets",
    "covariance_regularization",
    "dimension_aware_tangent_variance_target",
    "level_height_tree_distance_targets_v1",
    "parent_child_margin_loss",
    "parent_negative_coverage_statistics",
    "topology_safe_parent_negative_mask",
    "invariant_mass",
    "level_reconstruction_loss",
    "grafei_inter_loss",
    "grafei_intra_loss",
    "grafei_radius_loss",
    "link_metrics",
    "link_cross_entropy",
    "matching_cost",
    "momentum_metrics",
    "p4_sum_consistency_loss",
    "pdg_metrics",
    "plain_momentum_metrics",
    "radius_depth_loss",
    "radius_targets",
    "variance_regularization",
    "recover_pdg",
    "soft_daughter_sum_p4",
    "toy_mc_inter_loss",
    "toy_mc_radius_loss",
    "transfer_link_metrics",
    "vicreg_loss",
]
